# Generated by Django 6.0 on 2026-01-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_remove_department_problem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'user'), ('EMPLOYEE', 'employee'), ('ADMIN', 'admin')], default='USER', max_length=10),
        ),
    ]
