# Generated by Django 6.0 on 2026-01-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
