# Generated by Django 6.0 on 2026-01-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_alter_userprofile_area_alter_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('ROAD', 'road'), ('WATER', 'water'), ('ELECTRICITY', 'electricity'), ('SANITATION', 'sanitation'), ('GARBAGE', 'garbage'), ('general', 'general')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('LOW', 'low'), ('MEDIUM', 'medium'), ('HIGH', 'high')], default='MEDIUM', max_length=10),
        ),
    ]
